version: '3'
services:
  frontend:
    build: ./frontend  # Path to your React frontend Dockerfile
    ports:
      - "3000:80"  # Map port 80 (inside the container) to port 3000 (on your machine)
    depends_on:
      - backend  # Ensure the backend starts before the frontend
    environment:
      - NODE_ENV=production

  backend:
    build: ./backend  # Path to your Node.js backend Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 (inside the container) to port 5000 (on your machine)
    env_file: 
      - ./backend/.env
    environment:
      - NODE_ENV=production

  # because we are using mongodb using atlas no need to create separate database service